name = "AlpacaMarkets"
uuid = "02dc6022-739e-4478-acf8-ef45d2bc67b8"
authors = ["dm13450 <dean.markwick@talk21.com>"]
version = "0.1.5"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
DataFrames = "1"
HTTP = "1"
JSON = "0.21"
julia = "1"
